"""Generate the recorded game's id -> subject table, and audit the vocabulary.

The recorded game names things by NUMBER: `building_id 12`, `technology_id
249`. Loom names them by WORD, because it reads them off the screen. Nothing
in either half connects the two, so `replay_truth` carried a table of sixteen
ids I had corroborated by hand - and `run_report` silently skipped every id
that was not in it, which was most of them.

Two sources, and which is which matters:

* **The numbers come from `aoc-reference-data`** (SiegeEngineers, the dataset
  `aocref` packages and `mgz.reference` looks for). Nothing else here has
  them. Corroborated before it was trusted: all twenty ids I had derived
  independently from pixel evidence agree with it exactly, names included.

* **Which of those ids are KEPT is decided by Loom**, not by the dataset. For
  every name, this asks `glyphs.parse_event` whether Loom would produce an
  event if the game printed that line. If it would not, the id is left out
  and REPORTED. A ruler must only carry subjects the thing it measures can
  actually say; an id whose name Loom can never emit would score zero forever
  and look like a reader fault.

That filter had to be `parse_event` rather than the icon library, and the
difference is not cosmetic. `lines.subjects()` is derived from icon
FILENAMES, so it holds `infantry pikeman` and `pikeman up` - from
`Aoe2-infantry-2-pikeman.webp` and `PikemanUpDE.webp` - and no plain
`pikeman`. Loom emits `researched:pikeman` all the same, because the event
parser has its own vocabulary. Filtering on the icons dropped a subject Loom
demonstrably reads.

The audit is the useful by-product. A name the dataset has and Loom cannot
parse is a hole in `KNOWN_WORDS`, and that list fails SILENTLY - it refuses
perfectly-read lines and nothing anywhere reports it. This reports it.

    python -m tools.build_id_table            # what it would write, and the gaps
    python -m tools.build_id_table --write    # write loom/replay_ids.py
"""

# I used Anthropic's Claude to help with proper syntax, code organisation,
# debugging and review. The design and code are my own work.

import argparse
import json
import os
import sys
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from loom import glyphs, paths  # noqa: E402

DATASET_URL = ("https://raw.githubusercontent.com/SiegeEngineers/"
               "aoc-reference-data/master/data/datasets/100.json")

OUT_PATH = paths.PROJECT_ROOT / "loom" / "replay_ids.py"

# What the game prints when each kind of thing happens. Asking Loom to parse
# a whole line rather than a bare word is deliberate: the word alone is not
# what the reader ever sees, and a subject that only parses out of context
# is not one this table should carry.
BUILT = "--{} Built--"
RESEARCHED = "--{} Research Complete--"


def fetch_dataset(url=DATASET_URL):
    with urllib.request.urlopen(url, timeout=60) as handle:
        return json.loads(handle.read().decode("utf-8"))


# What parse_event returns for a line, minus the action. Two shapes come
# back and only one has a colon: `--Barracks Built--` gives `built:barracks`,
# while `--Town Center Built--` gives `town_center_built` - the PHRASE
# watcher's naming, because town centres are read by notifications.py and
# reader.py discards the glyph reader's version of them.
#
# Rejecting the second shape dropped the most consequential subject in the
# project from the table, and it was the cross-check against twenty
# hand-derived ids that caught it, not the generator.
ACTIONS = ("_built", "_created", "_research_complete", "_destroyed", "_found")


def subject_for(name, template):
    """The subject Loom would emit for this line, or None if it would not."""
    event = glyphs.parse_event(template.format(name))
    if not event:
        return None
    if ":" in event:
        return event.split(":", 1)[1]
    for action in ACTIONS:
        if event.endswith(action):
            return event[:-len(action)]
    return event


def table_for(named, template):
    """(id -> subject) for what Loom can say, and the names it cannot."""
    keep, refused = {}, {}
    for ident, name in named.items():
        if not name or not name.strip():
            continue
        subject = subject_for(name.strip(), template)
        if subject:
            keep[int(ident)] = subject
        else:
            refused.setdefault(name.strip(), []).append(int(ident))
    return keep, refused


def render(objects, technologies, version):
    lines = [
        '"""Recorded game ids, and what Loom calls the thing each one is.',
        "",
        "GENERATED by tools/build_id_table.py - do not edit by hand.",
        "",
        f"Numbers from aoc-reference-data dataset 100 (game data {version}).",
        "Which ids appear was decided by asking glyphs.parse_event whether",
        "Loom would emit an event for that name, so every subject here is one",
        "the reader can actually produce. Names Loom cannot parse are left",
        "out and listed by the generator, because an id whose subject Loom",
        "can never say would score zero forever and read as a reader fault.",
        '"""',
        "",
        "BUILDINGS = {",
    ]
    for ident in sorted(objects):
        lines.append(f"    {ident}: {objects[ident]!r},")
    lines += ["}", "", "TECHNOLOGIES = {"]
    for ident in sorted(technologies):
        lines.append(f"    {ident}: {technologies[ident]!r},")
    lines += ["}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--write", action="store_true",
                        help=f"write {OUT_PATH.name} rather than only report")
    arguments = parser.parse_args()

    data = fetch_dataset()
    version = (data.get("dataset") or {}).get("version", "?")
    objects, no_object = table_for(data["objects"], BUILT)
    technologies, no_tech = table_for(data["technologies"], RESEARCHED)

    print(f"dataset 100, game data {version}")
    print(f"  objects      {len(data['objects']):>5} -> {len(objects):>4} "
          f"Loom can name")
    print(f"  technologies {len(data['technologies']):>5} -> "
          f"{len(technologies):>4} Loom can name")

    # The audit. A name here is a line the game can print and Loom would
    # refuse, which is a hole in KNOWN_WORDS - and that list fails silently.
    refused = sorted(set(no_tech) & set(no_object))
    print(f"\n  {len(refused)} names Loom cannot parse in EITHER form. Each is"
          f" a line the game\n  can print and the reader would refuse:")
    for name in refused[:40]:
        print(f"      {name}")
    if len(refused) > 40:
        print(f"      ... and {len(refused) - 40} more")

    if arguments.write:
        OUT_PATH.write_text(render(objects, technologies, version),
                            encoding="utf-8")
        print(f"\nwrote {OUT_PATH}")
    else:
        print("\n(nothing written - pass --write)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
